### ISSUE TITLE
Update library for react-app-rewired >= 2.0.0

### ISSUE THREAD

**Issue by cmedinasoriano** [dashed/react-app-rewire-babel-loader#2]
Can this be updated for react-app-rewired@2.x.x?  I am using it in a project that relies on latest version of react-app-rewired but npm gives me the warning
`npm WARN react-app-rewired@1.6.2 requires a peer of react-scripts@^1.0.14 but none is installed. You must install peer dependencies yourself.` obviously because of react-app-rewire-babel-loader's dependencies.

I am more than happy to do it myself but I am not sure what is really needed for this to work with react-app-rewired >= 2.0.0.  I've been using it for a while and haven't seen any problem loading new libraries.

**Comment by dashed** [comment]
@cmedinanovettan Hi! Unfortunately, I won't be maintaining this library for `react-app-rewired` v2.x.x+. 😞 

I highly suggest consider using this library instead: https://github.com/arackaf/customize-cra

They have `babelInclude()` utility function built-in: https://github.com/arackaf/customize-cra/tree/01057dfd475a6739122bb2e751b32409309737c6#babelinclude

Below essentially emulates `react-app-rewire-babel-loader` which you can you use for your override file:

```js
// NOTE as of customize-cra v0.2.11

const { babelInclude, getBabelLoader } = require("customize-cra");

const include = (config, ...includes) => {
    return babelInclude(includes)(config);
};

const babelExclude = exclude => config => {
  getBabelLoader(config).exclude = exclude;
  return config;
};

const exclude = (config, ...excludes) => {
    return babelExclude(excludes)(config);
};
```
